version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: mentecart_backend
    ports:
      - "4040:4040"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge